### ISSUE TITLE
Update data model to comply with new requirements

### ISSUE THREAD

**Issue by HadleyKing** [UCI-GREGoR/retool#10]
Greta to talk with Seth for requirements
- [ ] Add solve_status, missing_variant_case, missing_variant_details in participants table
 - [ ] for next data upload - participant tab for now.

**Comment by lightning-auriga** [comment]
I didn't realize that this hadn't been updated. Do you happen to know if the aforementioned requirements are being enforced for this upload cycle, ending 12/29?
