### ISSUE TITLE
Collect User Stories

### ISSUE THREAD

**Issue by HadleyKing** [UCI-GREGoR/retool#13]
Distribute the following template for collection of user stories: https://github.com/UCI-GREGoR/retool/issues/new?assignees=&labels=&projects=&template=user_story.md&title=

**Comment by lightning-auriga** [comment]
That's a neat idea, I hope there's buy-in

**Comment by HadleyKing** [comment]
@lightning-auriga wanna take the lead? 

I think I translated the asks you had sent by email here already to issues but if you want to edit or elaborate on those feel free. I am from an 'open science' background so anything I put out is up for community input.
